import { Controller } from '@hotwired/stimulus'
// NOTE: CodeMirror modules come from the single vendored 'codemirror-json' bundle
// (vendor/javascript/codemirror-json.js — esbuild of @codemirror/view, state, commands,
// search, language, autocomplete + lang-json). Separate CDN pins load duplicate
// @codemirror/state instances, which break extension instanceof checks
// ("Unrecognized extension value in extension set") — do NOT re-split these imports.
// The bundle is loaded lazily on first use (dynamic import) so that a failure to
// resolve/load it cannot prevent this whole controller from registering: without it
// the edit modal would still open (Bootstrap data-toggle) but stay empty.
let _codemirrorJsonPromise = null
const loadCodeMirrorJson = () => {
  if (!_codemirrorJsonPromise) _codemirrorJsonPromise = import('codemirror-json')
  return _codemirrorJsonPromise
}

// Some association attributes are rendered under a different base entity name
// (mirrors Grid::EditModalComponent#detail_endpoint_name / #base_entity_name):
const RENAMED_ID_FIELD_KEYS = { associated_user_id: 'user_id', home_team_id: 'team_id' }

/**
 * = grid-edit - StimulusJS controller =
 *
 * Wrapper for JS methods used for single row edit in DataGrids.
 *
 * This will create a new controller instance for each configured "edit" button of the grid.
 *
 * Each button will yield a customized payload, which can be an empty attribute hash (Object) in the case
 * of a new record, or a hash with the values of a specific row record in case of actual edits.
 *
 * Some specific widgets are supported, depending on input type or specific DOM Ids used:
 * - `${attribute_key}-chk` - checkbox (boolean)
 * - `#json-editor-${attribute_key}` - JSON editor (text)
 *
 * Assumes also that a EditModalComponent is present in the DOM (accessed through its ID as set in the values).
 *
 * == Targets ==
 * (none)
 *
 * == Values ==
 * (Put values directly on controller elements)
 * @param {String} 'data-grid-edit-base-modal-id-value':
 *                 Base DOM ID of the modal target;
 *                 the modal will be filled-in with the values provided as payload.
 *
 * @param {String} 'data-grid-edit-url-value':
 *                 URL string for the update PUT action.
 *
 * @param {String} 'data-grid-edit-modal-edit-title-value':
 *                 string title for the edit modal dialog when the edit mode is set
 *                 (if the payload['id'] is *NOT* null).
 *
 * @param {String} 'data-grid-edit-modal-create-title-value':
 *                 string title for the edit modal dialog when the create mode is set
 *                 (if the payload['id'] is null).
 *
 * @param {Array} 'data-grid-edit-payload-value' (required)
 *                 JSON-ified ActiveRecord model instance of the row that has to be edited.
 *                 (Basically, an object map of keys mapped to values; each key will be editable,
 *                  except the 'id', if given)
 *
 * == Actions:
 * - <tt>handleEdit</tt> => fill the target modal form and display it.
 *
 * == Assumptions:
 * - <tt>"<BASE_MODAL_DOM_ID>-modal"</tt>
 *   => DOM ID of the modal container; the input fields (& labels) are assumed to be already generated by the component,
 *   according to the attributes stored in the payload.
 *
 * - <tt>"frm-<BASE_MODAL_DOM_ID>"</tt>
 *   => DOM ID of the internal Form storing the input fields for the "Grid Edit modal".
 *
 * - <tt>"btn-<BASE_MODAL_DOM_ID>-submit-save"</tt>
 *   => DOM ID of the submit button for saving the edits made using the internal Form.
 *
 * - <tt>"<BASE_MODAL_DOM_ID>-modal-title"</tt>
 *   => DOM ID of the label displaying the localized title string specified in the values
 *      ("data-grid-edit-modal-edit-title-value" or "data-grid-edit-modal-create-title-value").
 *
 * == Dependencies:
 * - CodeMirror 6: https://codemirror.net/
 * - @codemirror/lang-json: JSON language support
 *
 * @author Steve A.
 */
export default class extends Controller {
  static targets = ['form']
  static values = {
    baseModalId: String,
    url: String,
    modalEditTitle: String,
    modalCreateTitle: String,
    payload: Object
  }


  // DEBUG
  /**
   * Controller constructor.
   * Prepares also the JSONEditor instances for the dynamic form fields.
   */
  // initialize () {
  //   console.log('initialize()')
  // }

  // DEBUG
  /**
   * Setup invoked each time the controller instance connects.
   */
  // connect () {
  //   console.log('connect()')
  // }

  /**
   * Prepares all the input fields on the unique modal form, setting eventually any special checkbox or
   * JSONEditor fields found, so that the form can have a proper payload on POST.
   */
  handleEdit(event) {
    // DEBUG
    // console.log('handleEdit() action')
    event.preventDefault()

    if (this.hasBaseModalIdValue && this.hasUrlValue && this.hasPayloadValue) {
      // DEBUG
      // console.log('urlValue:')
      // console.log(this.urlValue)

      // Fix defaults for modal: (title, hidden _method & submit button method)
      if (this.payloadValue['id'] == null) {
        const modalTitle = document.getElementById(`${this.baseModalIdValue}-modal-title`)
        if (modalTitle) modalTitle.textContent = this.modalCreateTitleValue
        const methodInput = document.querySelector(`#frm-${this.baseModalIdValue} input[name='_method']`)
        if (methodInput) methodInput.value = 'post'
        const submitBtn = document.getElementById(`btn-${this.baseModalIdValue}-submit-save`)
        if (submitBtn) submitBtn.setAttribute('method', 'post')
      }
      else {
        const modalTitle = document.getElementById(`${this.baseModalIdValue}-modal-title`)
        if (modalTitle) modalTitle.textContent = this.modalEditTitleValue
        const methodInput = document.querySelector(`#frm-${this.baseModalIdValue} input[name='_method']`)
        if (methodInput) methodInput.value = 'patch'
        const submitBtn = document.getElementById(`btn-${this.baseModalIdValue}-submit-save`)
        if (submitBtn) submitBtn.setAttribute('method', 'put')
      }
      // Fix form target URL:
      const form = document.getElementById(`frm-${this.baseModalIdValue}`)
      if (form) form.action = this.urlValue

      // Make sure Turbo doesn't mess with the actual CSRF token of the form partial:
      const csrfInput = document.querySelector(`#frm-${this.baseModalIdValue} input[name='authenticity_token']`)
      const csrfMeta = document.querySelector("meta[name='csrf-token']")
      if (csrfInput && csrfMeta && csrfInput.value !== csrfMeta.getAttribute('content')) {
        csrfInput.value = csrfMeta.getAttribute('content')
      }

      // DEBUG
      // console.log(this.payloadValue)
      const nameSpaceBase = (this.baseModalIdValue == 'grid-edit' || this.baseModalIdValue == '' || this.baseModalIdValue == null) ?
                            '' : `${this.baseModalIdValue}_`
      // DEBUG
      console.log(`nameSpaceBase: '${nameSpaceBase}'`)

      Object.entries(this.payloadValue)
        .forEach(
          ([key, value]) => {
            // Use a namespaced selector only when the modal ID is present or different from the default:
            const namespacedFieldDomId = `${nameSpaceBase}${key}`
            // DEBUG
            // console.log(`Processing key: ${key} => Field DOM ID: #${namespacedFieldDomId}`)
            try {
              this._fillModalField(nameSpaceBase, namespacedFieldDomId, key, value)
            } catch (err) {
              // A single bad key/value must not prevent the remaining fields from being filled:
              console.error(`grid-edit: error filling field "${key}"`, err)
            }
          }
        )
      return true
    }
    return false
  }

  // Resolves the DOM id of the input that should hold the value for the given payload key.
  _fieldDomIdForKey (nameSpaceBase, key) {
    const mappedKey = RENAMED_ID_FIELD_KEYS[key] || key
    return `${nameSpaceBase}${mappedKey}`
  }

  _fillModalField (nameSpaceBase, namespacedFieldDomId, key, value) {
    // ** Checkbox fields: **
    // (use specific & unique DOM input fields, inside modal form)
    const checkbox = document.getElementById(`${namespacedFieldDomId}-chk`)
    if (checkbox && checkbox.type === 'checkbox') {
      // DEBUG
      // console.log('Checkbox field found')
      // Hidden field also available? Add a toggle/change event handler:
      const hiddenField = document.getElementById(namespacedFieldDomId)
      if (hiddenField && hiddenField.type === 'hidden') {
        checkbox.addEventListener('change', (event) => {
          const currState = event.target.checked
          const newValue = (currState == true) || (currState == 'true') ? '1' : '0'
          hiddenField.value = newValue
          hiddenField.dispatchEvent(new Event('change', { bubbles: true }))
          checkbox.value = newValue
        })
      }
      // Setup initial hidden field & checkbox value
      const initialValue = (value == true) || (value == 'true')
      checkbox.checked = initialValue
      checkbox.dispatchEvent(new Event('change', { bubbles: true }))
      return
    }

    // ** CodeMirror JSON editor fields: **
    // (use specific & unique DOM containers, inside modal form)
    const container = document.querySelector(`#json-editor-${namespacedFieldDomId}`)
    if (container) {
      // DEBUG
      // console.log('Possible JSON-editor field found')
      const hiddenField = document.getElementById(namespacedFieldDomId)
      if (hiddenField) hiddenField.value = value // Set initial value into hidden field

      let jsonDoc
      try {
        jsonDoc = JSON.stringify(JSON.parse(value), null, 2)
      } catch (_err) {
        // Not valid JSON (e.g. null/empty/plain text): still open the editor with the raw content
        jsonDoc = (value == null) ? '' : `${value}`
      }

      // Editor already created? Initialize its contents (from the row payload):
      if (container.codemirrorView) {
        // DEBUG
        // console.log(`CodeMirror instance found for "#${namespacedFieldDomId}": setting field value...`)
        container.codemirrorView.dispatch({
          changes: { from: 0, to: container.codemirrorView.state.doc.length },
          insert: jsonDoc
        })
      }
      else {
        // DEBUG
        // console.log(`Creating CodeMirror instance for "#${namespacedFieldDomId}"...`)
        const payloadKey = key
        loadCodeMirrorJson().then(cm => {
          container.codemirrorView = new cm.EditorView({
            doc: jsonDoc,
            extensions: [
              cm.lineNumbers(),
              cm.highlightActiveLineGutter(),
              cm.highlightSpecialChars(),
              cm.history(),
              cm.foldGutter(),
              cm.drawSelection(),
              cm.keymap.of([cm.defaultKeymap, cm.historyKeymap, cm.foldKeymap]),
              cm.autocompletion(),
              cm.rectangularSelection(),
              cm.crosshairCursor(),
              cm.highlightSelectionMatches(),
              cm.bracketMatching(),
              cm.EditorView.updateListener.of((update) => {
                if (update.docChanged) {
                  const jsonText = update.state.doc.toString()
                  // DEBUG
                  // console.log(`CodeMirror for "#${namespacedFieldDomId}" changed...`)
                  // Update both the row payload & the form's actual hidden field value:
                  this.payloadValue[payloadKey] = jsonText
                  const field = document.getElementById(namespacedFieldDomId)
                  if (field) {
                    field.value = jsonText
                    field.dispatchEvent(new Event('change', { bubbles: true }))
                  }
                }
              }),
              cm.json()
            ],
            parent: container
          })
        }).catch(err => console.error(`grid-edit: unable to load the JSON editor for "${namespacedFieldDomId}"`, err))
      }
      return
    }

    // ** "Standard" input fields: **
    // (any other input field using attribute "key" as DOM Id)
    // DEBUG
    // console.log(`Processing "#${namespacedFieldDomId}" standard input field...`)
    const field = document.getElementById(namespacedFieldDomId) ||
                  document.getElementById(this._fieldDomIdForKey(nameSpaceBase, key))
    if (field) {
      field.value = value
      field.dispatchEvent(new Event('change', { bubbles: true }))
    }
  }
  // ---------------------------------------------------------------------------
}
