// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import ChartApiController from "./chart_api_controller"
application.register("chart-api", ChartApiController)

import CodedNameController from "./coded_name_controller"
application.register("coded-name", CodedNameController)

import CollapseAllController from "./collapse_all_controller"
application.register("collapse-all", CollapseAllController)

import GridEditController from "./grid_edit_controller"
application.register("grid-edit", GridEditController)

import GridSelectionController from "./grid_selection_controller"
application.register("grid-selection", GridSelectionController)

import LookupController from "./lookup_controller"
application.register("lookup", LookupController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import RemotePartialController from "./remote_partial_controller"
application.register("remote-partial", RemotePartialController)

import SwitchController from "./switch_controller"
application.register("switch", SwitchController)

import UnsavedChangesController from "./unsaved_changes_controller"
application.register("unsaved-changes", UnsavedChangesController)
