// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller.js"
application.register("autocomplete", AutocompleteController)

import ChartApiController from "./chart_api_controller.js"
application.register("chart-api", ChartApiController)

import GridEditController from "./grid_edit_controller.js"
application.register("grid-edit", GridEditController)

import GridSelectionController from "./grid_selection_controller.js"
application.register("grid-selection", GridSelectionController)

import LookupController from "./lookup_controller.js"
application.register("lookup", LookupController)

import PopoverController from "./popover_controller.js"
application.register("popover", PopoverController)

import RemotePartialController from "./remote_partial_controller.js"
application.register("remote-partial", RemotePartialController)

import SwitchController from "./switch_controller.js"
application.register("switch", SwitchController)

import UnsavedChangesController from "./unsaved_changes_controller.js"
application.register("unsaved-changes", UnsavedChangesController)
