require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 165
  Exclude:
    - 'bin/bundle'

Metrics/AbcSize:
  Max: 26
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'
    - 'app/controllers/import_queues_controller.rb'
    - 'app/controllers/settings_controller.rb'
    - 'app/controllers/users_controller.rb'
    - 'app/controllers/pull_controller.rb'

Metrics/BlockLength:
  Max: 40
  CountAsOne: ['array', 'heredoc']
  Exclude:
    - 'bin/bundle'
    - 'config/routes.rb'
    - 'db/schema.rb'
    - 'lib/tasks/fixtures_from_results.rake'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'app/controllers/data_fix_controller.rb'
    - 'app/controllers/pull_controller.rb'
    - 'app/strategies/import/macro_committer.rb'
    - 'app/strategies/import/macro_solver.rb'

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 35
  Exclude:
    - 'db/migrate/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'


Rails/OutputSafety:
  Exclude:
    - 'app/grids/*'

# Excluded files here were already corrected in later migrations:
Rails/ThreeStateBooleanColumn:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/20210513113601_create_goggles_db_user_workshops.rb'
    - 'db/migrate/20220228114607_add_cancelled_to_calendars.rb'
    - 'db/migrate/20220801110842_add_sql_batch_field_to_import_queues.rb:6'


Rake/MethodDefinitionInTask:
  Exclude:
    - 'lib/tasks/pdfs_from_results.rake'


RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false


Style/ClassAndModuleChildren:
  Exclude:
  - 'api/**/*'

Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/application.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
