development:
  adapter: async

test:
  adapter: test

production:
  # [Steve A.] This must be run only on localhost, so no Redis instance is needed:
  adapter: async
  channel_prefix: admin2_production
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
