# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'root' } %>
  # Use socket for localhost connections only; otherwise, use 'host' or 'url' parameters:
  socket: /var/run/mysqld/mysqld.sock
  # host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  # port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>

development:
  <<: *default
  database: goggles_development
  password: NothingIs4ever!

test:
  <<: *default
  database: goggles_test
  password: NothingIs4ever!

production:
  <<: *default
  database: goggles
  password: NothingIs4ever!

# [Steve A.]
# Staging will use the production environment together with the database
# running on the production Docker image of the composed service
# (DockerHub: steveoro/goggles-api:latest) with the exception of enforcing SSL
# to allow local testing.
#
# To recreate or restore a usable database with testing seeds, assuming:
#
# 1. you have a valid 'test.sql.bz2' dump file stored under 'db/dumps';
# 2. the DB container 'goggles-db' is already running;
#
# Execute the dedicated task:
#
#   $> RAILS_ENV=staging rails db:rebuild from=test to=staging
#
staging:
  <<: *default
  database: goggles
  password: NothingIs4ever!
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 33060 } %>
